site_name: BOTOY - OPQ的Python助手

repo_name: xiyaowong/botoy
repo_url: https://github.com/xiyaowong/botoy

theme:
  name: material
  palette:
    primary: purple

nav:
  - index.md
  - client.md
  - config.md
  - middleware.md
  - decorators.md
  - refine.md
  - action.md
  - plugin.md
  - session.md
  - webhook.md
  - schedule.md
  - contrib.md
  - async.md
  - cli.md
  - other.md
  - changelog.md

markdown_extensions:
  - codehilite
  - admonition
  - tables
  - toc:
      permalink: '#'
  - markdown_include.include:
      base_path: docs
