site_name: BOTOY - OPQ的Python助手

repo_url: https://github.com/xiyaowong/botoy

theme:
  name: material

nav:
  - overview.md
  - client.md
  - config.md
  - middleware.md
  - decorators.md
  - refine.md
  - action.md
  - plugin.md
  - async.md
  - cli.md
  - other.md
  - changelog.md

markdown_extensions:
  - codehilite
  - admonition
  - tables
  - toc:
      permalink: '#'
